services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    networks:
      adguard_macvlan:
        ipv4_address: 192.168.1.53
      bearslions_network: {}
    volumes:
      - ${APPDATA_PATH}/adguard/work:/opt/adguardhome/work
      - ${APPDATA_PATH}/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=${TZ}
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"

networks:
  adguard_macvlan:
    name: adguard_macvlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.53/32

  bearslions_network:
    external: true