services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - GENERIC_TIMEZONE=${TZ}
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=https
      - N8N_TRUST_PROXY=true
      - N8N_PROXY_HOPS=1
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

      # --- INYECCIONES PARA LA BASE DE DATOS DE TRACKING ---
      - N8N_ALLOW_ENV_VARIABLES=true # Permite que n8n lea variables del sistema en expresiones
      - PROPTECH_DB_HOST=postgres # Apunta al container_name del nuevo stack de Postgres
      - PROPTECH_DB_PORT=5432         # Puerto interno de comunicación en la red de Docker
      - PROPTECH_DB_NAME=${PROPTECH_DB_NAME}
      - PROPTECH_DB_USER=${PROPTECH_DB_USER}
      - PROPTECH_DB_PASSWORD=${PROPTECH_DB_PASSWORD}
    volumes:
      - ${APPDATA_PATH}/n8n:/home/node/.n8n
    ports:
      - "5678:5678"
    deploy:
      resources:
        limits:
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    networks:
      - bearslions_network

networks:
  bearslions_network:
    external: true