services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest_tracker
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SPEEDTEST_SCHEDULE=0 * * * *
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=config/database.sqlite
    volumes:
      - ${APPDATA_PATH}/speedtest-tracker:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    networks:
      - bearslions_network

networks:
  bearslions_network:
    external: true