services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      # DNS: Estos sí deben ser los estándar para que tus dispositivos los usen
      - "53:53/tcp"
      - "53:53/udp"
      # Panel de Control: Cambiamos el 80 por el 3030 para evitar conflictos con UGOS
      - "3030:80/tcp"   # <--- Panel web en el 3030
      - "3030:3000/tcp" # <--- Instalador inicial en el 3030
    volumes:
      - ${APPDATA_PATH}/adguard/work:/opt/adguardhome/work
      - ${APPDATA_PATH}/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=${TZ}
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    networks:
      - bearslions_network

networks:
  bearslions_network:
    external: true