services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      # Usamos la variable definida en global.env
      - ${APPDATA_PATH}/uptime-kuma:/app/data
      # Socket de Docker en modo solo lectura por seguridad
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "3001:3001"
    # Protección de almacenamiento contra logs infinitos
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"

networks:
  bearslions_network:
    external: true
    