services:
  nocodb-db:
    image: postgres:16-alpine
    container_name: nocodb-postgres
    restart: always
    environment:
      POSTGRES_DB: nocodb_db
      POSTGRES_USER: noco_user
      POSTGRES_PASSWORD: ${NOCODB_DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - /volume2/docker/appdata/nocodb/pg_data:/var/lib/postgresql/data
    networks:
      - bearslions

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb-app
    restart: always
    environment:
      NC_DB: "pg://nocodb-postgres:5432?u=noco_user&p=${NOCODB_DB_PASSWORD}&d=nocodb_db"
    ports:
      - "8085:8080"
    depends_on:
      - nocodb-db
    networks:
      - bearslions

networks:
  bearslions:
    external: true