services:
  baserow:
    container_name: baserow
    image: baserow/baserow:1.30.0 # Es recomendable fijar versión
    restart: always
    environment:
      BASEROW_PUBLIC_URL: "http://192.168.1.225:8086" # Cambia por tu IP o dominio
    ports:
      - "8086:80"
    volumes:
      - /volume2/docker/appdata/baserow:/baserow/data
    networks:
      - bearslions_network

networks:
  bearslions_network:
    external: true